"""Shared foundation contracts for Reel-Mind."""

from reel_mind.foundation.config import ConfigLoader, config_version_hash, deep_merge
from reel_mind.foundation.errors import (
    BudgetExceeded,
    ConfigError,
    IdempotencyConflict,
    ReelMindError,
    RetryableError,
    RetryableStorageError,
    SecretError,
    StorageError,
    TerminalError,
    TerminalStorageError,
)
from reel_mind.foundation.models import (
    AdaptersConfig,
    ApprovalMode,
    ArtifactKind,
    ArtifactRef,
    ChannelConfig,
    ChannelId,
    CostBucket,
    ErrorRecord,
    LedgerEntry,
    Pipeline,
    PipelineRun,
    RunState,
    StageRecord,
    StageStatus,
    Trigger,
    WarmupPhase,
)
from reel_mind.foundation.secrets import OAuthRefreshResult, SecretsProvider, secret_env_name

__all__ = [
    "AdaptersConfig",
    "ApprovalMode",
    "ArtifactKind",
    "ArtifactRef",
    "BudgetExceeded",
    "ChannelConfig",
    "ChannelId",
    "ConfigError",
    "ConfigLoader",
    "CostBucket",
    "ErrorRecord",
    "IdempotencyConflict",
    "LedgerEntry",
    "Pipeline",
    "PipelineRun",
    "ReelMindError",
    "RetryableError",
    "RetryableStorageError",
    "RunState",
    "SecretError",
    "SecretsProvider",
    "StageRecord",
    "StageStatus",
    "StorageError",
    "TerminalError",
    "TerminalStorageError",
    "Trigger",
    "WarmupPhase",
    "config_version_hash",
    "deep_merge",
    "secret_env_name",
    "OAuthRefreshResult",
]
