"""Shared foundation contracts for Reel-Mind."""

from reel_mind.foundation.config import ConfigLoader, config_version_hash, deep_merge
from reel_mind.foundation.cost import CostLedger
from reel_mind.foundation.errors import (
    BudgetExceeded,
    ConfigError,
    IdempotencyConflict,
    ReelMindError,
    RetryableError,
    RetryableStorageError,
    SecretError,
    StorageError,
    TerminalError,
    TerminalStorageError,
)
from reel_mind.foundation.idempotency import canonicalize_slot, run_id_for
from reel_mind.foundation.logging import RedactionProcessor, get_logger, init_logger, redact_value
from reel_mind.foundation.models import (
    AdaptersConfig,
    ApprovalMode,
    ArtifactKind,
    ArtifactRef,
    ChannelConfig,
    ChannelId,
    CostBucket,
    ErrorRecord,
    LedgerEntry,
    Pipeline,
    PipelineRun,
    RunState,
    StageRecord,
    StageStatus,
    Trigger,
    WarmupPhase,
)
from reel_mind.foundation.retry import (
    LEDGER_CRITICAL,
    STORAGE_DEFAULT,
    Classification,
    ClassificationKind,
    RetryExecutor,
    RetryPolicy,
    classify_http_like,
)
from reel_mind.foundation.runs import RunRecorder
from reel_mind.foundation.secrets import OAuthRefreshResult, SecretsProvider, secret_env_name
from reel_mind.foundation.storage import (
    R2Client,
    SupabaseClient,
    r2_key,
    validate_r2_key,
)

__all__ = [
    "AdaptersConfig",
    "ApprovalMode",
    "ArtifactKind",
    "ArtifactRef",
    "BudgetExceeded",
    "ChannelConfig",
    "ChannelId",
    "ConfigError",
    "ConfigLoader",
    "CostLedger",
    "CostBucket",
    "ErrorRecord",
    "IdempotencyConflict",
    "LedgerEntry",
    "Pipeline",
    "PipelineRun",
    "R2Client",
    "RedactionProcessor",
    "ReelMindError",
    "RetryExecutor",
    "RetryPolicy",
    "RetryableError",
    "RetryableStorageError",
    "RunState",
    "RunRecorder",
    "SecretError",
    "SecretsProvider",
    "StageRecord",
    "StageStatus",
    "StorageError",
    "SupabaseClient",
    "TerminalError",
    "TerminalStorageError",
    "Trigger",
    "WarmupPhase",
    "canonicalize_slot",
    "classify_http_like",
    "config_version_hash",
    "deep_merge",
    "get_logger",
    "init_logger",
    "redact_value",
    "run_id_for",
    "secret_env_name",
    "r2_key",
    "validate_r2_key",
    "OAuthRefreshResult",
    "Classification",
    "ClassificationKind",
    "LEDGER_CRITICAL",
    "STORAGE_DEFAULT",
]
